name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-bush@v4
      with:
        image: noor66/hello-flask
        registry: docker.io
        username: ${{ secrets.NAMEDOCKER }}
        password: ${{ secrets.PASSDOCKER }} 
